### ISSUE TITLE
Swiper 4 support

### ISSUE THREAD

**Issue by andymark-by** [dev7ch/drupal-swiper#1]
Do you plan support Swiper 4 (>4.3.3) version on Drupal 8?
Now I seen: 
> Swiper library not found. Please consult the README.md for installation instructions.

**Comment by andymark-by** [comment]
Sorry, install version from Git and message disappeared =)

**Comment by dev7ch** [comment]
@andymark-by this isn´t really ready to use version, it was quick shot fix of an outdated drupal module.

There is no plan to extend or continuing this module, it is just the result of a closer look the swiper moduel in relation to Drupal.

But your problem could be related to the file path of the swiper library.

https://github.com/dev7ch/drupal-swiper/blob/3b3370afa1ca12d4c6335a3d9132bd3e37378fed/swiper.module#L26

Libraries is currently not correctly used, wich mean `dist/js/swiper.js` is from where the lib is loaded.

Tipp: After spending a few hours with this outdated module i generated my own new views-style-formatter with drupal-console and implementation of swiper went super good (which was all i needed)

**Comment by dev7ch** [comment]
@andymark-by closing due inacitvity?
